03_정수론
Altu-Bitu-6/Altu-Bitu-MoonJaewon pull request #8
Opened 2024-03-04 17:01 UTC by lumiere-on

학번: 2276107
이름: 문재원

##과제 제출
기존 제출: 1735, 6588
추가 제출: 2840

2024-03-06 15:02 UTC, chae-jpg requested changes
**[정수론 이론 코드리뷰 완료]**

1735(P1), 6588(P3)
재원님 안녕하세요! 코드 리뷰 완료되었습니다👍
현제 1735번 문제에서 오답 판정이 나오고 있습니다 😢 리뷰 확인해보시고 수정한 뒤 다시 리뷰어 호출 부탁드립니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-06 15:02 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +        n=order.at(j);
order[j]로도 표현 가능합니다!

2024-03-06 15:02 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +                break;
합이 두 소수로 이루어진 경우를 구해둔 소수 여부 배열을 이용해서 잘 찾아주셨어요!

2024-03-08 06:19 UTC, kimhj010502 approved these changes
**[정수론 구현 문제 코드 리뷰 완료]**

재원님 안녕하세요!
과제하시느라 수고 많으셨습니다!!
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-08 06:31 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

1735(P3)
재원님 안녕하세요! 코드 수정 정상적으로 확인되었습니다! 수고하셨습니다~
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-10 12:36 UTC, merged